---
- name: install required apt repos
  apt_repository:
    repo: 'ppa:ubuntu-mozilla-daily/firefox-aurora'
    state: present

- name: install package goodness
  apt:
    name: firefox
    state: latest
    update_cache: true
