---
- hosts: localhost
  become: true

  vars:
    - golang_version: '1.9'
    - nodejs_version: '8.9.3'

  roles:
    - { role: git, tags: 'git' }
    - { role: zsh, tags: 'zsh' }
    - { role: neovim, tags: 'neovim' }
    - { role: firefox, tags: 'firefox' }
    - { role: asdf, tags: 'asdf' }
    - { role: golang, tags: 'golang' }
    - { role: nodejs, tags: 'nodejs' }
    - { role: keybase, tags: 'keybase' }
    - { role: exa, tags: 'exa' }
    - { role: kr, tags: 'kr' }

  tasks:
    - name: upgrade system and existing packages
      apt:
        upgrade: dist
        autoclean: true
        autoremove: true
        update_cache: true
