---
- name: fetch asdf repo
  become: false
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: v0.4.0

- name: install recommended apt packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - automake
    - autoconf
    - libreadline-dev
    - libncurses-dev
    - libssl-dev
    - libyaml-dev
    - libxslt-dev
    - libffi-dev
    - libtool
    - unixodbc-dev
  when: ansible_distribution == "Ubuntu"

- name: source in zshrc
  become: false
  blockinfile:
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK - asdf"
    block: |
      . $HOME/.asdf/asdf.sh
      . $HOME/.asdf/completions/asdf.bash
