---
- name: install zsh
  apt:
    name: zsh
    state: present
  register: zsh
  when: ansible_distribution == "Ubuntu"

- name: install zsh
  pacman:
    name: zsh
    state: latest
  register: zsh
  when: ansible_distribution == "Archlinux"

- name: fetch ohmyzsh repo
  become: false
  git:
    repo: git://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
  when: zsh|changed

- name: assumes username is liam, proceed?
  pause:
  when: zsh|changed

- name: set default shell
  command: chsh -s /usr/bin/zsh liam
  when: zsh|changed

- name: set zsh theme
  become: false
  lineinfile:
    path: ~/.zshrc
    regexp: '^ZSH_THEME.*$'
    line: 'ZSH_THEME="juanghurtado"'
    backrefs: true

