---
- name: install packages
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - htop
    - httpie
    - noto-fonts-emoji
    - tmux
    - ttf-hack
    - ttf-symbola
    - vlc-nightly
  when: ansible_distribution == "Archlinux"

- name: set up emoji font fallback
  copy:
    src: local.conf
    dest: /etc/fonts/local.conf
