---
- name: install keybase
  apt:
    deb: https://prerelease.keybase.io/keybase_amd64.deb
  register: keybase

- name: finishing install
  become: false
  command: run_keybase
  when: keybase|changed
