---
- include_tasks: install_ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include_tasks: install_arch.yml
  when: ansible_distribution == "Archlinux"

- name: install neovim pip packages
  pip:
    name: neovim

- name: create config folder
  become: false
  file:
    path: ~/.config/nvim/
    state: directory
    recurse: true

- name: install configs
  become: false
  copy:
    src: generate.vim
    dest: ~/.config/nvim/init.vim

- name: update shells for neovim (https://github.com/neovim/neovim/issues/5990)
  lineinfile:
    path: "{{ item }}"
    line: 'export VTE_VERSION="100"'
  with_items:
    - /etc/zsh/zprofile
    - /etc/profile

- name: source in zshrc
  become: false
  blockinfile:
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK - neovim"
    block: |
      alias vim="nvim"
